name: CI
on:
    workflow_dispatch:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]

jobs:
  Build_Test-Swift:
    runs-on: macos-14
    steps:
    - uses: actions/checkout@v3
    - name: Select Xcode version
      run: sudo xcode-select -s '/Applications/Xcode_15.4.app/Contents/Developer'
    - name: Swift Version
      run: swift --version
    - name: Build using Xcode
      run: xcodebuild -scheme GateEngineDemos-Package -destination "platform=macOS,name=Any Mac"
#     - name: Test using Xcode
#       run: xcodebuild -scheme GateEngineDemos-Package -destination "platform=macOS,name=Any Mac" test
